apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata: 
  name: {{.Values.chartName}}-deployment
spec:
  selector:
    matchLabels:
      app: {{.Values.chartName}}
  replicas: {{.Values.container.replica}} # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: {{.Values.chartName}}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: {{.Values.container.image}}
        ports:
        - containerPort: 80