apiVersion: extensions/v1beta1
kind: Ingress
metadata: |
  name: {{{.Values.chartName}}-ingress
spec:
  backend:
    serviceName: {{.Values.chartName}}-service
    servicePort: 8081
  rules:
  - host: 
    http:
      paths:
      - path: /test
        backend:
          serviceName: {{.Values.chartName}}-service
          servicePort: 8081
