apiVersion: v1
kind: Service
metadata: |
  name: {{ template "kubelab-chart.fullname" . }}-service
spec:
  type: NodePort
  selector:
    app: {{ template "kubelab-chart.fullname" . }}
  ports:
  - port: 8081
    targetPort: 80
    nodePort: 31000 # this is optional as it can be automatically picked between the range of 30000 - 32767
